{**
---
license: LGPL-2.1-only WITH Independent-modules-exception
copyright: Copyright 2026 Liam Seamus Coughlin
keywords: http2, example, binary, body writer
notes:
  - This example answers with a generated byte buffer of a set size.
  - The body goes out through a pull writer, so the handler holds no copy of
    the whole body at once.
---
}
/// A server that answers with generated binary bytes
// - the program shows IBodyWriter, the pull writer of the response
program binary_response;

{$mode delphi}{$H+}
{$modeswitch advancedrecords}
{$interfaces com}

uses
  {$IFDEF UNIX}cthreads,{$ENDIF}
  SysUtils,
  mormot.core.base,
  Http2Server;

const
  /// how many octets the response holds
  BodyOctets = 1024 * 64;
  /// how many octets one chunk holds
  ChunkOctets = 4096;

type
  /// the pull writer that generates the body chunk by chunk
  TBytesBodyWriter = class(TInterfacedObject, IBodyWriter)
  private
    FLeft: Integer;
    FSeed: Byte;
  public
    constructor Create(const AOctets: Integer);
    function NextChunk(out ABuffer: TBytes): Boolean;
  end;

  /// the handler of the example
  TBinaryHandler = class(TInterfacedObject, IHttp2Handler)
  public
    procedure Handle(const ARequest: IServerRequest;
      const AResponse: IServerResponse);
  end;

constructor TBytesBodyWriter.Create(const AOctets: Integer);
begin
  inherited Create;
  FLeft := AOctets;
  FSeed := 1;
end;

function TBytesBodyWriter.NextChunk(out ABuffer: TBytes): Boolean;
var
  N, I: Integer;
begin
  ABuffer := nil;
  if FLeft <= 0 then
    Exit(False);
  N := ChunkOctets;
  if N > FLeft then
    N := FLeft;
  SetLength(ABuffer, N);
  for I := 0 to N - 1 do
  begin
    ABuffer[I] := FSeed;
    Inc(FSeed);
  end;
  Dec(FLeft, N);
  // False ends the response, so the writer answers False on the last call
  Result := FLeft > 0;
end;

procedure TBinaryHandler.Handle(const ARequest: IServerRequest;
  const AResponse: IServerResponse);
var
  Headers: THeaderBlock;
begin
  SetLength(Headers, 1);
  Headers[0].Name := 'content-type';
  Headers[0].Value := 'application/octet-stream';
  AResponse.SendHeaders(200, Headers, False);
  AResponse.SetBodyWriter(TBytesBodyWriter.Create(BodyOctets));
  AResponse.Finish;
end;

var
  Server: IHttp2Server;
  Line: string;
begin
  Server := THttp2ServerFactory.Create
    .WithHost('127.0.0.1')
    .WithPort(8080)
    .WithClearTextAllowed(True)
    .WithHandler(TBinaryHandler.Create)
    .Build;
  Server.Start;
  Writeln('the server listens on port ', Server.Port, ' (h2c)');
  Writeln('a GET answers ', BodyOctets, ' generated octets');
  Writeln('press Enter to stop');
  Readln(Line);
  Server.Stop;
end.
