{**
---
license: TBD-LICENCE
copyright: Copyright 2026 Liam Seamus Coughlin
keywords: http2, example, interop, echo, large body, binary
notes:
  - This example is the server that the validation runs drive.  It answers a
    text page, a generated body of a requested size, a byte range of all 256
    values, and an echo of a request body.
  - The port comes from the first argument, so a validation script holds the
    port.  A port of zero leaves the port to the operating system, and the
    program prints the port it received.
  - The program runs until it reads a line on the standard input, so a
    script stops it by closing the input.
---
}
/// The server that the validation runs drive
// - answers `/` with text, `/large?bytes=N` with generated bytes, `/binary`
//   with every byte value once, and `POST /echo` with the request body
program interop_server;

{$mode delphi}{$H+}
{$modeswitch advancedrecords}
{$interfaces com}

uses
  {$IFDEF UNIX}cthreads,{$ENDIF}
  SysUtils,
  mormot.core.base,
  Http2Server;

const
  /// the size of one write to the response
  ChunkBytes = 65536;
  /// the size of the generated body of `/large` with no query
  DefaultLargeBytes = 1048576;

type
  /// the body writer of a generated response
  ///
  /// The writer produces a repeated byte pattern, so a large body needs no
  /// large buffer in the program.
  TPatternWriter = class(TInterfacedObject, IBodyWriter)
  private
    FLeft: Int64;
    FChunk: TBytes;
  public
    constructor Create(const ATotal, AChunkSize: Int64);
    function NextChunk(out ABuffer: TBytes): Boolean;
  end;

  /// the handler of the validation server
  TInteropHandler = class(TInterfacedObject, IHttp2Handler)
  private
    procedure WriteText(const AResponse: IServerResponse; const AStatus: Integer;
      const AText: string);
  public
    procedure Handle(const ARequest: IServerRequest;
      const AResponse: IServerResponse);
  end;

{ TPatternWriter }

constructor TPatternWriter.Create(const ATotal, AChunkSize: Int64);
var
  Index: Integer;
begin
  inherited Create;
  FLeft := ATotal;
  SetLength(FChunk, AChunkSize);
  for Index := 0 to AChunkSize - 1 do
    FChunk[Index] := Byte(Index mod 251);
end;

function TPatternWriter.NextChunk(out ABuffer: TBytes): Boolean;
var
  Count: Integer;
begin
  Result := FLeft > 0;
  if not Result then
  begin
    ABuffer := nil;
    Exit;
  end;
  Count := Length(FChunk);
  if Int64(Count) > FLeft then
    Count := FLeft;
  SetLength(ABuffer, Count);
  Move(FChunk[0], ABuffer[0], Count);
  Dec(FLeft, Count);
end;

{ TInteropHandler }

procedure TInteropHandler.WriteText(const AResponse: IServerResponse;
  const AStatus: Integer; const AText: string);
var
  Body: TBytes;
begin
  SetLength(Body, Length(AText));
  if Length(AText) > 0 then
    Move(AText[1], Body[0], Length(AText));
  AResponse.SendHeaders(AStatus, nil, False);
  AResponse.Write(Body);
  AResponse.Finish;
end;

procedure TInteropHandler.Handle(const ARequest: IServerRequest;
  const AResponse: IServerResponse);
var
  Path: string;
  Query: string;
  LargeBytes: Int64;
  Equal: Integer;
  Value: Int64;
  Body: TBytes;
  Read: Integer;
  Total: Integer;
  Chunk: TBytes;
begin
  Path := ARequest.Path;
  Equal := Pos('?', Path);
  Query := '';
  if Equal > 0 then
  begin
    Query := Copy(Path, Equal + 1, MaxInt);
    Path := Copy(Path, 1, Equal - 1);
  end;

  if Path = '/large' then
  begin
    LargeBytes := DefaultLargeBytes;
    if Copy(Query, 1, 6) = 'bytes=' then
      if TryStrToInt64(Copy(Query, 7, MaxInt), Value) and (Value >= 0) then
        LargeBytes := Value;
    AResponse.SendHeaders(200, nil, False);
    AResponse.SetBodyWriter(TPatternWriter.Create(LargeBytes, ChunkBytes));
    AResponse.Finish;
    Exit;
  end;

  if Path = '/binary' then
  begin
    SetLength(Body, 256);
    for Read := 0 to 255 do
      Body[Read] := Byte(Read);
    AResponse.SendHeaders(200, nil, False);
    AResponse.Write(Body);
    AResponse.Finish;
    Exit;
  end;

  if Path = '/echo' then
  begin
    SetLength(Body, 0);
    Total := 0;
    // pull the request body in chunks, so a large upload needs no large buffer
    while ARequest.ReadChunk(Chunk) do
    begin
      if Length(Chunk) = 0 then
        Continue;
      SetLength(Body, Total + Length(Chunk));
      Move(Chunk[0], Body[Total], Length(Chunk));
      Inc(Total, Length(Chunk));
    end;
    AResponse.SendHeaders(200, nil, False);
    AResponse.Write(Body);
    AResponse.Finish;
    Exit;
  end;

  if Path = '/' then
  begin
    WriteText(AResponse, 200,
      'the validation server answered ' + ARequest.Method + ' ' +
      ARequest.Path + sLineBreak);
    Exit;
  end;

  WriteText(AResponse, 404, 'no such path' + sLineBreak);
end;

var
  Server: IHttp2Server;
  Port: Integer;
  Line: string;
  BigBucket, StrictBucket: TTokenBucketOptions;
  Strict: Boolean;
  Factory: THttp2ServerFactory;
begin
  // the validation runs drive a large body, so the control-frame rate limits
  // must not fire.  The server keeps one control bucket: it takes the least
  // capacity of the five, so all five are raised together.  The second
  // argument `strict` lowers every control bucket, so the abuse tool can
  // reach the limits.
  BigBucket := TTokenBucketOptions.Create
    .WithCapacity(100000000)
    .WithRefillPerSecond(100000000);
  StrictBucket := TTokenBucketOptions.Create
    .WithCapacity(20)
    .WithRefillPerSecond(1)
    .WithCostBeforeDispatch(1)
    .WithCostAfterDispatch(1);
  Port := 0;
  if ParamCount >= 1 then
    Port := StrToIntDef(ParamStr(1), 0);
  Strict := (ParamCount >= 2) and (ParamStr(2) = 'strict');
  Factory := THttp2ServerFactory.Create
    .WithHost('127.0.0.1')
    .WithPort(Port)
    .WithClearTextAllowed(True)
    .WithHandler(TInteropHandler.Create)
    .WithHandlerThreads(4)
    .WithIOThreads(2);
  if Strict then
    Factory := Factory
      .WithResetBucket(StrictBucket)
      .WithPingBucket(StrictBucket)
      .WithSettingsBucket(StrictBucket)
      .WithEmptyDataBucket(StrictBucket)
      .WithWindowUpdateBucket(StrictBucket)
      .WithContinuationBucket(StrictBucket)
      .WithMaxHeaderListSize(8192)
      .WithHeaderTimeout(2000);
  Server := Factory.Build;
  Server.Start;
  Writeln('the validation server listens on port ', Server.Port, ' (h2c)');
  Flush(Output);
  // a script keeps this process alive by holding the standard input open
  while not Eof(Input) do
    Readln(Line);
  Server.Stop;
  Writeln('the validation server stopped');
end.
